import type { PathwayCatalogue, PathwayItem } from "./pathways-types.js";

const ALL_BOARDS = [
  "CBSE",
  "ICSE",
  "STATE",
  "CAMBRIDGE",
  "IB",
] as const satisfies PathwayItem["boardFamilies"];

function item(
  partial: PathwayItem
): PathwayItem {
  return partial;
}

export const PATHWAYS_CATALOGUE: PathwayCatalogue = {
  schemaVersion: 1,
  items: [
    item({
      slug: "cbse-stay-middle",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: ["middle"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Stay on CBSE",
      summary: "Grade 9–10 comes next; no stream yet.",
      lead: "Middle school is for building habits. Stream choice is still two years away.",
      detailRows: [
        { label: "When", value: "Grade 6–8" },
        { label: "Next", value: "Class 10 board years" },
        { label: "Stream", value: "Not yet" },
        { label: "Opens", value: "Later: PCM, PCB, Commerce, Arts" },
        { label: "Look at", value: "Optional olympiads only" },
        { label: "Not this", value: "Not JEE foundation season" },
      ],
      requiredDetailRowLabels: ["When", "Next", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 10,
    }),
    item({
      slug: "cbse-stream-peek",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: [],
      previewStageIds: ["middle"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Later: five Class 11 streams",
      summary: "PCM · PCB · PCMB · Commerce · Arts.",
      lead: "After Class 10, CBSE families choose a stream for 11–12. This is a peek, not a choice this year.",
      detailRows: [
        { label: "When", value: "After Class 10" },
        { label: "Options", value: "PCM, PCB, PCMB, Commerce, Arts" },
        { label: "Opens", value: "Entrance papers in Grade 11–12" },
        { label: "Also", value: "Switch board or polytechnic" },
        { label: "Status", value: "Peek only in middle school" },
        { label: "Not this", value: "Not a decision this year" },
      ],
      requiredDetailRowLabels: ["When", "Options", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 20,
    }),
    item({
      slug: "cbse-aisse",
      kind: "exam",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: ["board_10"],
      previewStageIds: ["middle"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: ["cbse_10"],
      title: "Class 10 (AISSE)",
      summary: "First public exam. Feeds the stream choice.",
      lead: "CBSE Class 10 boards feed the Class 11 stream choice. They do not replace JEE or NEET.",
      detailRows: [
        { label: "Also known as", value: "CBSE 10th boards" },
        { label: "When", value: "Grade 10" },
        { label: "Subjects", value: "Board set for the school" },
        { label: "Eligibility", value: "CBSE Class 10" },
        { label: "Opens", value: "Stream choice for 11–12" },
        { label: "Not this", value: "Not JEE or NEET" },
      ],
      requiredDetailRowLabels: [
        "Also known as",
        "When",
        "Subjects",
        "Eligibility",
        "Opens",
        "Not this",
      ],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.cbse.gov.in/",
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 30,
    }),
    item({
      slug: "cbse-after-10-streams",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Stay in CBSE 11–12",
      summary: "Pick PCM, PCB, PCMB, Commerce, or Arts.",
      lead: "After Class 10, most families stay on CBSE and choose a stream for Grades 11–12.",
      detailRows: [
        { label: "When", value: "After Class 10 results" },
        { label: "Structure", value: "Two years · Class 11–12" },
        { label: "Streams", value: "PCM, PCB, PCMB, Commerce, Arts" },
        { label: "Opens", value: "Board exams plus entrances" },
        { label: "Also", value: "Switch board or polytechnic" },
        { label: "Not this", value: "Not a coaching prescription" },
      ],
      requiredDetailRowLabels: ["When", "Structure", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 40,
    }),
    item({
      slug: "cbse-switch-board",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Switch board",
      summary: "ISC, IB Diploma, or Cambridge A Level.",
      lead: "After Class 10, some families move to ISC, IB Diploma, or Cambridge A Level. It costs a year of new assessment style.",
      detailRows: [
        { label: "When", value: "After Class 10" },
        { label: "Options", value: "ISC · IBDP · A Level" },
        { label: "Keep CBSE if", value: "JEE / NEET coaching alignment" },
        { label: "Opens", value: "That board’s senior path" },
        { label: "Cost", value: "New assessment style for a year" },
        { label: "Not this", value: "Not advice to leave CBSE" },
      ],
      requiredDetailRowLabels: ["When", "Options", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 50,
    }),
    item({
      slug: "tg-polycet",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE", "ICSE", "STATE"],
      stateCodes: ["TG"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all", "vocational"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Polytechnic",
      summary: "After Class 10 · POLYCET in Telangana.",
      lead: "A diploma after Class 10 via POLYCET, with optional later B.Tech entry through ECET.",
      detailRows: [
        { label: "When", value: "After Class 10" },
        { label: "Exam", value: "POLYCET · Telangana" },
        { label: "Opens", value: "Engineering diploma" },
        { label: "Later", value: "ECET lateral entry to B.Tech" },
        { label: "Eligibility", value: "Class 10 pass" },
        { label: "Not this", value: "Not EAPCET / not MBBS" },
      ],
      requiredDetailRowLabels: ["When", "Exam", "Opens", "Not this"],
      admissionPattern: "own_cet",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://polycet.sbtet.telangana.gov.in/",
      sourceUrls: [
        "https://polycet.sbtet.telangana.gov.in/",
        "https://tgpolycet.nic.in/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 60,
    }),
    item({
      slug: "cbse-aissce",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CBSE"],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: ["cbse_12"],
      title: "Class 12 (AISSCE)",
      summary: "Board marks run beside entrance papers.",
      lead: "CBSE Class 12 boards and entrance exams run in the same year. Board marks matter for some state routes.",
      detailRows: [
        { label: "When", value: "Grade 12" },
        { label: "Structure", value: "Board + entrances together" },
        { label: "Opens", value: "Indian UG and some state counselling" },
        { label: "Also", value: "Predicted interest abroad optional" },
        { label: "Eligibility", value: "CBSE Class 12" },
        { label: "Not this", value: "Not a substitute for NEET or JEE" },
      ],
      requiredDetailRowLabels: ["When", "Structure", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.cbse.gov.in/",
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 70,
    }),
    item({
      slug: "after-12-routes",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["after_12"],
      previewStageIds: ["senior"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "After 12 — Indian UG / abroad",
      summary: "Counselling, CUET, professional courses, or UCAS.",
      lead: "After school, routes split into national counselling, state seats, CUET universities, professional courses, or abroad applications.",
      detailRows: [
        { label: "When", value: "After Class 12 / DP / A Level" },
        { label: "India", value: "JoSAA, state counselling, CUET" },
        { label: "Professional", value: "CA, law, design, NDA" },
        { label: "Abroad", value: "UCAS / Common App where relevant" },
        { label: "Opens", value: "College applications" },
        { label: "Not this", value: "Not a rank predictor" },
      ],
      requiredDetailRowLabels: ["When", "India", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://jeemain.nta.nic.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 80,
    }),
    item({
      slug: "ioqm",
      kind: "olympiad",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["middle", "board_10"],
      previewStageIds: ["foundation"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "IOQM / maths olympiad",
      summary: "National maths path. Not IIT selection.",
      lead: "IOQM is the national maths olympiad entry. It is optional and is not an IIT selection exam.",
      detailRows: [
        { label: "When", value: "Middle school onward" },
        { label: "Subjects", value: "Mathematics" },
        { label: "Eligibility", value: "School enrolment rules apply" },
        { label: "Opens", value: "INMO pathway" },
        { label: "Kind", value: "HBCSE olympiad" },
        { label: "Not this", value: "Not JEE / not commercial SOF" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Opens", "Not this"],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://ioqm.mtai.org.in/",
      sourceUrls: [
        "https://ioqm.mtai.org.in/",
        "https://olympiads.hbcse.tifr.res.in/mathematical-olympiad-2026-2027/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 90,
    }),
    item({
      slug: "school-olympiads",
      kind: "olympiad",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["middle", "board_10"],
      previewStageIds: ["foundation"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "School olympiads",
      summary: "Optional practice. Commercial, not selection.",
      lead: "School-level contests can be useful practice. They are commercial and are not national selection exams.",
      detailRows: [
        { label: "When", value: "Middle / Class 10 years" },
        { label: "Subjects", value: "Varies by contest" },
        { label: "Eligibility", value: "School registration" },
        { label: "Opens", value: "Practice only" },
        { label: "Kind", value: "School-level / commercial" },
        { label: "Not this", value: "Not IIT or NEET selection" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 100,
    }),
    item({
      slug: "jee-main",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["middle", "board_10"],
      streamIds: ["pcm", "pcmb"],
      contrastForStreamIds: ["pcb", "commerce", "arts"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "JEE Main",
      summary: "NITs, IIITs · gate to JEE Advanced.",
      lead: "Opens NITs, IIITs, GFTIs, and the gate to JEE Advanced. IGCSE and MYP alone are not enough.",
      detailRows: [
        { label: "Also known as", value: "JEE Mains" },
        { label: "When", value: "Grade 11–12 / A Level / DP" },
        { label: "Subjects", value: "Physics, chemistry, maths" },
        { label: "Eligibility", value: "Class 12 equivalent with PCM" },
        { label: "Opens", value: "NIT / IIIT / GFTI · Advanced" },
        { label: "Not this", value: "Not the IIT paper" },
      ],
      requiredDetailRowLabels: [
        "Also known as",
        "When",
        "Subjects",
        "Eligibility",
        "Opens",
        "Not this",
      ],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://jeemain.nta.nic.in/",
      sourceUrls: ["https://jeemain.nta.nic.in/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 110,
    }),
    item({
      slug: "jee-advanced",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["pcm", "pcmb"],
      contrastForStreamIds: ["pcb", "commerce", "arts"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "JEE Advanced",
      summary: "IITs, after qualifying Main.",
      lead: "The IIT paper. Sit it only after qualifying JEE Main, with Physics, Chemistry, and Maths in Class 12 equivalent.",
      detailRows: [
        { label: "When", value: "Grade 12 sitting window" },
        { label: "Requires", value: "JEE Main qualify" },
        { label: "Subjects", value: "Physics, chemistry, maths" },
        { label: "Eligibility", value: "Class 12 equivalent with PCM" },
        { label: "Opens", value: "IITs" },
        { label: "Not this", value: "Not JEE Main itself" },
      ],
      requiredDetailRowLabels: [
        "When",
        "Requires",
        "Subjects",
        "Eligibility",
        "Opens",
        "Not this",
      ],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://jeeadv.ac.in/",
      sourceUrls: ["https://jeeadv.ac.in/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 120,
    }),
    item({
      slug: "neet-ug",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["middle", "board_10"],
      streamIds: ["pcb", "pcmb"],
      contrastForStreamIds: ["pcm", "commerce", "arts"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "NEET UG",
      summary: "MBBS, BDS, AYUSH. Mandatory for medicine.",
      lead: "The only undergraduate medical exam in India. EAPCET is not a substitute.",
      detailRows: [
        { label: "When", value: "Grade 11–12 / A Level / DP" },
        { label: "Subjects", value: "Physics, chemistry, biology" },
        { label: "Eligibility", value: "Class 12 equivalent with PCB" },
        { label: "Opens", value: "MBBS, BDS, AYUSH" },
        { label: "Counselling", value: "MCC AIQ + state quota" },
        { label: "Not this", value: "EAPCET is not medicine" },
      ],
      requiredDetailRowLabels: [
        "When",
        "Subjects",
        "Eligibility",
        "Opens",
        "Counselling",
        "Not this",
      ],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://neet.nta.nic.in/",
      sourceUrls: ["https://neet.nta.nic.in/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 130,
    }),
    item({
      slug: "tg-eapcet",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["TG"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["pcm", "pcb", "pcmb"],
      contrastForStreamIds: ["commerce", "arts"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "TG EAPCET",
      summary: "State B.Tech / agri / pharmacy. Not MBBS.",
      lead: "Telangana’s state entrance for engineering, agriculture, and pharmacy. Medicine uses NEET.",
      detailRows: [
        { label: "Also known as", value: "EAMCET, TS EAMCET" },
        { label: "When", value: "Class 12-equivalent year" },
        { label: "Subjects", value: "PCM engineering; PCB agri/pharmacy" },
        { label: "Eligibility", value: "Class 12 equivalent" },
        { label: "Opens", value: "TG B.Tech, agriculture, pharmacy" },
        { label: "Local rule", value: "Check local / non-local brochure" },
        { label: "Not this", value: "MBBS — medicine is NEET" },
      ],
      requiredDetailRowLabels: [
        "Also known as",
        "When",
        "Subjects",
        "Eligibility",
        "Opens",
        "Local rule",
        "Not this",
      ],
      admissionPattern: "own_cet",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://eapcet.tgche.ac.in/",
      sourceUrls: [
        "https://eapcet.tgche.ac.in/",
        "https://tgeapcet.nic.in/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 140,
    }),
    item({
      slug: "cuet-ug",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["all", "commerce", "arts", "pcm", "pcb", "pcmb"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "CUET UG",
      summary: "Central and many participating universities.",
      lead: "CUET is used by central and many other universities. Class 12 equivalents include A Level and IB Diploma.",
      detailRows: [
        { label: "When", value: "Grade 12 / DP / A Level year" },
        { label: "Subjects", value: "Domain papers vary" },
        { label: "Eligibility", value: "Class 12 equivalent" },
        { label: "Opens", value: "Central / participating universities" },
        { label: "Also", value: "Useful for commerce and arts" },
        { label: "Not this", value: "Not JoSAA engineering counselling" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Eligibility", "Opens", "Not this"],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://cuet.nta.nic.in/",
      sourceUrls: ["https://cuet.nta.nic.in/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 150,
    }),
    item({
      slug: "clat",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["arts", "commerce", "all"],
      contrastForStreamIds: ["pcm", "pcb"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "CLAT",
      summary: "National law universities.",
      lead: "CLAT opens five-year law seats at National Law Universities.",
      detailRows: [
        { label: "When", value: "Grade 12 year" },
        { label: "Subjects", value: "Aptitude, English, GK, logic" },
        { label: "Eligibility", value: "Class 12 equivalent" },
        { label: "Opens", value: "NLUs · five-year law" },
        { label: "Also", value: "AILET for NLU Delhi" },
        { label: "Not this", value: "Not a science entrance" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Eligibility", "Opens", "Not this"],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://consortiumofnlus.ac.in/",
      sourceUrls: ["https://consortiumofnlus.ac.in/clat-2026/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 160,
    }),
    item({
      slug: "ca-foundation",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["senior", "after_12"],
      previewStageIds: ["board_10"],
      streamIds: ["commerce"],
      contrastForStreamIds: ["pcm", "pcb"],
      eligibleQualificationIds: [
        "cbse_12",
        "isc_12",
        "state_12",
        "a_level",
        "ib_dp",
      ],
      title: "CA Foundation",
      summary: "First gate for chartered accountancy.",
      lead: "CA Foundation is the first professional gate after Class 12 equivalent. Registration can start earlier.",
      detailRows: [
        { label: "When", value: "After Class 12 · register earlier" },
        { label: "Subjects", value: "Accounts, law, maths, economics" },
        { label: "Eligibility", value: "Class 12 equivalent" },
        { label: "Opens", value: "CA Intermediate path" },
        { label: "Also", value: "CSEET for CS path" },
        { label: "Not this", value: "Not CUET itself" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Eligibility", "Opens", "Not this"],
      admissionPattern: "national",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.icai.org/",
      sourceUrls: [
        "https://www.icai.org/",
        "https://www.icai.org/post/faqs-provisional-admission-to-foundation-course",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 170,
    }),
    item({
      slug: "ntse-inactive",
      kind: "exam",
      pillar: "opportunities",
      boardFamilies: [...ALL_BOARDS],
      stateCodes: ["IN"],
      stageIds: ["board_10", "middle"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "NTSE",
      summary: "Paused. Still searchable.",
      lead: "NTSE has been paused since the 2021 cycle. It stays in the catalogue so parents who search for it see the correct status.",
      detailRows: [
        { label: "When", value: "Historically Class 10" },
        { label: "Subjects", value: "MAT and SAT papers" },
        { label: "Eligibility", value: "No live cycle" },
        { label: "Opens", value: "Scholarship · inactive" },
        { label: "Status", value: "Paused" },
        { label: "Not this", value: "Not a current science route" },
      ],
      requiredDetailRowLabels: ["When", "Subjects", "Opens", "Not this"],
      admissionPattern: "national",
      contentDepth: "full",
      status: "inactive",
      officialUrl: "https://ncert.nic.in/national-talent-examination.php",
      sourceUrls: ["https://ncert.nic.in/national-talent-examination.php"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 900,
    }),
    item({
      slug: "ib-diploma",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["IB"],
      stateCodes: ["IN"],
      stageIds: ["after_10", "senior"],
      previewStageIds: ["board_10"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Diploma Programme",
      summary: "Stay in IB. 3 HL + 3 SL. AIU treats DP as Class 12-equivalent.",
      lead: "Two-year senior IB programme. AIU equates IB Diploma (and IB Course/Certificate at ≥24 points with 3 HL + 3 SL) with Indian +2. MYP is not a Class 12 equivalent. Colleges may still ask for an AIU certificate.",
      detailRows: [
        { label: "Also known as", value: "IBDP" },
        { label: "When", value: "After MYP · Grade 11–12" },
        { label: "Structure", value: "6 subjects · 3 HL + 3 SL" },
        { label: "India equivalent", value: "≥24 points · 3+3" },
        { label: "Subject gate", value: "PCM or PCB HLs for Indian routes" },
        { label: "Calendar", value: "May · results 6 July" },
        { label: "Opens", value: "UCAS · Indian UG if HLs match" },
        { label: "Not this", value: "Not IBCP · MYP ≠ UG" },
      ],
      requiredDetailRowLabels: [
        "When",
        "Structure",
        "India equivalent",
        "Subject gate",
        "Calendar",
        "Opens",
        "Not this",
      ],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.ibo.org/programmes/diploma-programme/",
      sourceUrls: [
        "https://www.ibo.org/programmes/diploma-programme/",
        "https://evaluation.aiu.ac.in/Documents/PDF/Ammendments%20in%20Equivalence%20in%20Informatin%20Brochure.pdf",
        "https://www.ibo.org/programmes/diploma-programme/assessment-and-exams/getting-results/assessment-faq/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 40,
    }),
    item({
      slug: "ib-cp",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["IB"],
      stateCodes: ["IN"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["vocational", "all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Career-related Programme",
      summary: "Vocational. Weaker Indian recognition than DP.",
      lead: "IBCP is vocational IB. Indian university recognition is narrower than the Diploma. Confirm with the college.",
      detailRows: [
        { label: "When", value: "After MYP" },
        { label: "Structure", value: "Career studies + DP courses" },
        { label: "India equivalent", value: "Case by case" },
        { label: "Opens", value: "Applied / vocational routes" },
        { label: "Confirm", value: "Each college’s IBCP list" },
        { label: "Not this", value: "Not a DP substitute" },
      ],
      requiredDetailRowLabels: ["When", "Structure", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.ibo.org/programmes/career-related-programme/",
      sourceUrls: ["https://www.ibo.org/programmes/career-related-programme/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 45,
    }),
    item({
      slug: "ib-to-cbse",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["IB"],
      stateCodes: ["IN"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Switch to CBSE 11–12",
      summary: "If JEE / NEET coaching alignment matters.",
      lead: "Some IB families move to CBSE 11–12 for Indian coaching calendars. Orientation only, not a recommendation.",
      detailRows: [
        { label: "When", value: "After MYP" },
        { label: "Structure", value: "CBSE PCM / PCB / Commerce / Arts" },
        { label: "Opens", value: "Same as CBSE senior" },
        { label: "Trade-off", value: "Leave IB breadth" },
        { label: "Also", value: "A Level is another switch" },
        { label: "Not this", value: "Not advice to leave IB" },
      ],
      requiredDetailRowLabels: ["When", "Structure", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://www.cbse.gov.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 46,
    }),
    item({
      slug: "ib-may-clash",
      kind: "admission_route",
      pillar: "opportunities",
      boardFamilies: ["IB"],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: ["ib_dp"],
      title: "May exam clash",
      summary: "DP papers overlap JEE, NEET, and state CETs.",
      lead: "May DP written papers collide with JEE, NEET, CUET, and most state CETs. Plan sittings; do not assume one paper replaces another.",
      detailRows: [
        { label: "When", value: "DP May session" },
        { label: "Results", value: "6 July" },
        { label: "Collides with", value: "JEE, NEET, CUET, EAPCET" },
        { label: "Use", value: "Predicted grades for provisional offers" },
        { label: "Then", value: "IB Indian transcript after results" },
        { label: "Not this", value: "Predicted grades ≠ sitting NEET/JEE" },
      ],
      requiredDetailRowLabels: ["When", "Results", "Collides with", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.ibo.org/programmes/diploma-programme/assessment-and-exams/getting-results/assessment-faq/",
      sourceUrls: [
        "https://www.ibo.org/programmes/diploma-programme/assessment-and-exams/getting-results/assessment-faq/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 35,
    }),
    item({
      slug: "ucas",
      kind: "admission_route",
      pillar: "opportunities",
      boardFamilies: ["IB", "CAMBRIDGE"],
      stateCodes: ["IN"],
      stageIds: ["senior"],
      previewStageIds: ["board_10"],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: ["ib_dp", "a_level"],
      title: "UCAS / Common App",
      summary: "Abroad applications in the senior year.",
      lead: "First-class abroad path for IB and Cambridge. Uses predicted grades, then final results. Does not replace NEET for Indian medicine.",
      detailRows: [
        { label: "When", value: "DP / A Level year" },
        { label: "Subjects", value: "Depends on course choice" },
        { label: "Eligibility", value: "DP or A Level" },
        { label: "Opens", value: "UK / US and other UG" },
        { label: "Also", value: "IELTS / TOEFL may still be asked" },
        { label: "Not this", value: "Not an Indian medical seat" },
      ],
      requiredDetailRowLabels: ["When", "Eligibility", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.ucas.com/",
      sourceUrls: ["https://www.ucas.com/"],
      lastReviewedOn: "2026-09-21",
      sortOrder: 36,
    }),
    item({
      slug: "cambridge-a-level",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["CAMBRIDGE"],
      stateCodes: ["IN"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Stay Cambridge — A Level",
      summary: "Choose 3–4 subjects for Indian and abroad routes.",
      lead: "After IGCSE, A Level subject choice becomes the Indian eligibility set. IGCSE alone is Class 10.",
      detailRows: [
        { label: "When", value: "After IGCSE" },
        { label: "Structure", value: "AS then A Level · 3–4 subjects" },
        { label: "India equivalent", value: "A Level = Class 12" },
        { label: "Subject gate", value: "PCM or PCB for Indian routes" },
        { label: "Calendar", value: "March series preferred for India" },
        { label: "Opens", value: "UCAS · JEE/NEET/CET if subjects match" },
        { label: "Not this", value: "IGCSE is not Class 12" },
      ],
      requiredDetailRowLabels: [
        "When",
        "Structure",
        "India equivalent",
        "Subject gate",
        "Calendar",
        "Opens",
        "Not this",
      ],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: "https://www.cambridgeinternational.org/",
      sourceUrls: [
        "https://www.cambridgeinternational.org/",
        "https://jeemain.nta.nic.in/",
      ],
      lastReviewedOn: "2026-09-21",
      sortOrder: 40,
    }),
    item({
      slug: "ssc-intermediate",
      kind: "pathway",
      pillar: "what_next",
      boardFamilies: ["STATE"],
      stateCodes: ["TG", "AP"],
      stageIds: ["after_10"],
      previewStageIds: [],
      streamIds: ["all"],
      contrastForStreamIds: [],
      eligibleQualificationIds: [],
      title: "Intermediate",
      summary: "MPC, BiPC, MEC, CEC, or HEC at junior college.",
      lead: "After SSC, most Telangana and Andhra families move to Intermediate. Local stream names replace PCM/PCB labels.",
      detailRows: [
        { label: "When", value: "After SSC" },
        { label: "Structure", value: "Two years · junior college" },
        { label: "Streams", value: "MPC, BiPC, MEC, CEC, HEC" },
        { label: "Opens", value: "EAPCET, NEET, CUET, JEE" },
        { label: "Also", value: "POLYCET is the diploma fork" },
        { label: "Not this", value: "Not CBSE Class 11 naming" },
      ],
      requiredDetailRowLabels: ["When", "Structure", "Streams", "Opens", "Not this"],
      admissionPattern: "not_applicable",
      contentDepth: "full",
      status: "published",
      officialUrl: null,
      sourceUrls: ["https://tgeapcet.nic.in/"],
      lastReviewedOn: "2026-03-01",
      sortOrder: 40,
    }),
  ],
  links: [
    { fromSlug: "cbse-after-10-streams", toSlug: "jee-main", rel: "leads_to" },
    { fromSlug: "cbse-after-10-streams", toSlug: "neet-ug", rel: "leads_to" },
    { fromSlug: "cbse-after-10-streams", toSlug: "tg-eapcet", rel: "leads_to" },
    { fromSlug: "jee-main", toSlug: "jee-advanced", rel: "leads_to" },
    { fromSlug: "jee-advanced", toSlug: "jee-main", rel: "requires" },
    { fromSlug: "tg-eapcet", toSlug: "cbse-aissce", rel: "requires" },
    { fromSlug: "ib-diploma", toSlug: "jee-main", rel: "leads_to" },
    { fromSlug: "ib-diploma", toSlug: "ucas", rel: "leads_to" },
    { fromSlug: "cambridge-a-level", toSlug: "ucas", rel: "leads_to" },
    { fromSlug: "ssc-intermediate", toSlug: "tg-eapcet", rel: "leads_to" },
  ],
};
