import { colors } from "@/constants/theme";

/** Child's Path tokens — same warm-white system as the rest of the app. */
export const pathTheme = {
  bg: colors.bg,
  navWordmark: colors.primary,
  navTitle: colors.text,
  navAction: colors.primary,
  eyebrow: colors.textMuted,
  title: colors.text,
  deck: colors.textMuted,
  nodeFill: colors.card,
  nodeBorder: colors.border,
  kicker: colors.textSubtle,
  nodeTitle: colors.text,
  nodeMeta: colors.textMuted,
  treeLine: colors.border,
  forkCaption: colors.textMuted,
  branchIdleFill: colors.card,
  branchIdleBorder: colors.border,
  branchIdleText: colors.text,
  branchIdleStatus: colors.textMuted,
  branchActiveFill: colors.primarySoft,
  branchActiveText: colors.primaryDark,
  branchActiveStatus: colors.primary,
  panelFill: colors.card,
  panelBorder: colors.border,
  chipIdleFill: colors.card,
  chipIdleBorder: colors.border,
  chipIdleText: colors.text,
  chipActiveFill: colors.primarySoft,
  chipActiveText: colors.primaryDark,
  promptKicker: colors.textSubtle,
  quote: colors.text,
  ctaFill: colors.primary,
  ctaText: colors.textInverse,
  textLink: colors.primary,
  lock: colors.textMuted,
  dimmed: colors.textSubtle,
} as const;
