-- West Hyderabad schools catalog from vaara Schools List - Hyd.xlsx
-- 208 unique school names (exact-name duplicates collapsed to one campus).
-- Target: Neon Postgres `schools` table.
-- Idempotent: ON CONFLICT (normalized_key) updates catalog fields.
-- City is always Hyderabad; Location column is stored as branch.
--
-- Collapsed exact-name duplicates:
--   Sanskriti School: kept Kondapur; sheet also had ['Kondapur', 'Manikonda', 'Puppalaguda']
--   Sreenidhi Global School: kept Gachibowli; sheet also had ['Kondapur', 'Gachibowli', 'Khajaguda']
--   Dibber International Preschool: kept Kondapur; sheet also had ['Kondapur', 'Banjara Hills']
--   Delhi Public School: kept Gachibowli; sheet also had ['Gachibowli', 'Khajaguda', 'Kollur']
--   Rockwell International School: kept Kokapet; sheet also had ['Gachibowli', 'Kokapet']
--   The Gaudium School: kept Kollur; sheet also had ['Gachibowli', 'Nanakramguda', 'Kollur']
--   Delhi School of Excellence: kept Manikonda; sheet also had ['Manikonda', 'Banjara Hills']
--   Scholars International School: kept Manikonda; sheet also had ['Manikonda', 'Puppalaguda']
--   Shanthinikethan Concept School: kept Manikonda; sheet also had ['Manikonda', 'Puppalaguda']

INSERT INTO schools (
  name, branch, city, state, pin_code, normalized_key, verified,
  board_codes, grades_offered
)
VALUES
  (
    'CHIREC International School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'chirec_international_school|kondapur|hyderabad',
    true,
    '{CBSE,IGCSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'Nursery-12'
  ),
  (
    'Arbor International School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'arbor_international_school|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery-10'
  ),
  (
    'Sanskriti School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'sanskriti_school|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary to Secondary Level'
  ),
  (
    'GVR Global Erudite School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'gvr_global_erudite_school|kondapur|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    'Nursery-10'
  ),
  (
    'Sumanjali High School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'sumanjali_high_school|kondapur|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    'Nursery-10'
  ),
  (
    'Ryan International School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'ryan_international_school|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery-7'
  ),
  (
    'Githanjali The Global School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'githanjali_the_global_school|kondapur|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Branwalton International School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'branwalton_international_school|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Samskruthi High School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'samskruthi_high_school|kondapur|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Sreenidhi Global School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'sreenidhi_global_school|gachibowli|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    NULL
  ),
  (
    'Sharada Vidya Niketan / Sharada High School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'sharada_vidya_niketan_sharada_high_school|kondapur|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    'Nursery-12'
  ),
  (
    'Maharishi Vidya Mandir - Kondapur/Kothaguda campus',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'maharishi_vidya_mandir_kondapur_kothaguda_campus|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery-12'
  ),
  (
    'Jain Heritage - A Cambridge School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'jain_heritage_a_cambridge_school|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    '1-10'
  ),
  (
    'Sri Krishnaveni Talent School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'sri_krishnaveni_talent_school|kondapur|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery-10'
  ),
  (
    'New Bloom High School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'new_bloom_high_school|kondapur|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery-10'
  ),
  (
    'Vidya Talent School - Whitefields/Kondapur',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'vidya_talent_school_whitefields_kondapur|kondapur|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery-10'
  ),
  (
    'Gowtham Model School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'gowtham_model_school|kondapur|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    'Nursery-10'
  ),
  (
    'World One School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'world_one_school|kondapur|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Nursery-10'
  ),
  (
    'Unicent School - Kondapur/Hafeezpet',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'unicent_school_kondapur_hafeezpet|kondapur|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Bachpan / Academic Heights Public School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'bachpan_academic_heights_public_school|kondapur|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Dibber International Preschool',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'dibber_international_preschool|kondapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Kangaroo Kids International Preschool',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool|kondapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool'
  ),
  (
    'Vivero International Preschool & Child Care',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'vivero_international_preschool_child_care|kondapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool'
  ),
  (
    'Calhoun Academy',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'calhoun_academy|kondapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool'
  ),
  (
    'Stepping Stone School',
    'Kondapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'stepping_stone_school|kondapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool'
  ),
  (
    'Goldcrest School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'goldcrest_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'K-10/12'
  ),
  (
    'AVN Vida International School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'avn_vida_international_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'K-12'
  ),
  (
    'EuroSchool Hyderabad',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'euroschool_hyderabad|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'K-12'
  ),
  (
    'Prerana Waldorf School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'prerana_waldorf_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Kendriya Vidyalaya',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'kendriya_vidyalaya|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'K-12'
  ),
  (
    'Vidya High School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'vidya_high_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'K-12'
  ),
  (
    'Delhi Public School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'delhi_public_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'Rockwell International School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'rockwell_international_school|kokapet|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'LKG / Primary - Grade 12'
  ),
  (
    'The Gaudium School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    '502300',
    'the_gaudium_school|kollur|hyderabad',
    true,
    '{CBSE,IGCSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'Oakridge International School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'oakridge_international_school|gachibowli|hyderabad',
    true,
    '{CBSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'K-12'
  ),
  (
    'My School ITALY',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'my_school_italy|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Ingenium Foundation School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'ingenium_foundation_school|gachibowli|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Ambitus World School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'ambitus_world_school|gachibowli|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    NULL
  ),
  (
    'Vista International School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'vista_international_school|gachibowli|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Silver Oaks International School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'silver_oaks_international_school|gachibowli|hyderabad',
    true,
    '{CBSE,IB_PYP,IB_MYP,IBDP}'::text[],
    NULL
  ),
  (
    'GEMS Wellington School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'gems_wellington_school|gachibowli|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'St. Ann''s High School',
    'Gachibowli',
    'Hyderabad',
    'Telangana',
    NULL,
    'st_ann_s_high_school|gachibowli|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Manthan International School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'manthan_international_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    NULL
  ),
  (
    'Meridian School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'meridian_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE,IB_PYP,IB_MYP,IBDP}'::text[],
    NULL
  ),
  (
    'The Global Edge School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_global_edge_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'CGR International School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'cgr_international_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Sloka The Global School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'sloka_the_global_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Santosh Reddy International School - HITEC City',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'santosh_reddy_international_school_hitec_city|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Gowtham Model School - HITEC City/Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'gowtham_model_school_hitec_city_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    NULL
  ),
  (
    'Narayana e-Techno School - Hitech City',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'narayana_e_techno_school_hitech_city|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'EuroSchool - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'euroschool_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Orchids The International School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'orchids_the_international_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Academic Heights Public School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'academic_heights_public_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Resonance School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'resonance_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Ybrant Smartek Schools - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'ybrant_smartek_schools_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Sharp High School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'sharp_high_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Nachiketa Vidya Mandir - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'nachiketa_vidya_mandir_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Swetcha School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'swetcha_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Velocity High School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'velocity_high_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Pioneer World School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'pioneer_world_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Madhapur High School',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'madhapur_high_school|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Goutham Model High School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'goutham_model_high_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Dev Guru School - Madhapur',
    'Madhapur / HITEC City',
    'Hyderabad',
    'Telangana',
    NULL,
    'dev_guru_school_madhapur|madhapur_hitec_city|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'The Shri Ram Universal School',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_shri_ram_universal_school|nanakramguda|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Sagebrook International School',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'sagebrook_international_school|nanakramguda|hyderabad',
    true,
    '{IB_PYP,IB_MYP,IBDP}'::text[],
    NULL
  ),
  (
    'Nanakramguda Government School',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'nanakramguda_government_school|nanakramguda|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'Vidyalok Educational Trust',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'vidyalok_educational_trust|nanakramguda|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'SVL School - Financial District',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'svl_school_financial_district|nanakramguda|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Little Einsteins Gachibowli',
    'Nanakramguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'little_einsteins_gachibowli|nanakramguda|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Delhi School of Excellence',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'delhi_school_of_excellence|manikonda|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary to Grade 10'
  ),
  (
    'Elate International School',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'elate_international_school|manikonda|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Early Years to Senior Grades'
  ),
  (
    'Scholars International School',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'scholars_international_school|manikonda|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary to Grade 10'
  ),
  (
    'Tejomayi Schools',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'tejomayi_schools|manikonda|hyderabad',
    true,
    '{SSC}'::text[],
    'Pre-Primary to Secondary'
  ),
  (
    'Shanthinikethan Concept School',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'shanthinikethan_concept_school|manikonda|hyderabad',
    true,
    '{}'::text[],
    'Pre-Primary to Secondary Level'
  ),
  (
    'Pavithra International School',
    'Manikonda',
    'Hyderabad',
    'Telangana',
    NULL,
    'pavithra_international_school|manikonda|hyderabad',
    true,
    '{}'::text[],
    'Pre-Primary to Secondary'
  ),
  (
    'National Premium School (NPS)',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'national_premium_school_nps|puppalaguda|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Early Years to Senior Grades'
  ),
  (
    'The Future Kid''s School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_future_kid_s_school|puppalaguda|hyderabad',
    true,
    '{ICSE}'::text[],
    'Primary to Grade 12'
  ),
  (
    'Keystone School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'keystone_school|puppalaguda|hyderabad',
    true,
    '{IGCSE}'::text[],
    'Early Years to Grade 12'
  ),
  (
    'Geetanjali Olympiad School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'geetanjali_olympiad_school|puppalaguda|hyderabad',
    true,
    '{}'::text[],
    'Nursery to Middle/Secondary Level'
  ),
  (
    'Exceed School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'exceed_school|puppalaguda|hyderabad',
    true,
    '{IGCSE}'::text[],
    'Early Years to Secondary Level'
  ),
  (
    'Rosebuds World School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'rosebuds_world_school|puppalaguda|hyderabad',
    true,
    '{}'::text[],
    'Pre-Primary to School Level'
  ),
  (
    'Sai Pallavi International School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'sai_pallavi_international_school|puppalaguda|hyderabad',
    true,
    '{}'::text[],
    'Primary / School Level'
  ),
  (
    'Hyderabad Grammar School',
    'Puppalaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'hyderabad_grammar_school|puppalaguda|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Scholars Academy',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'scholars_academy|neknampur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Senior Secondary - up to Grade 12'
  ),
  (
    'Elate INTERNATIONAL SCHOOL',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'elate_international_school|neknampur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Secondary Level - up to Grade 10'
  ),
  (
    'Azra Public School',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'azra_public_school|neknampur|hyderabad',
    true,
    '{CBSE,SSC}'::text[],
    'Pre-Primary to School Level'
  ),
  (
    'Vedamudra Vidya Public School',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'vedamudra_vidya_public_school|neknampur|hyderabad',
    true,
    '{}'::text[],
    'Pre-Primary & Primary'
  ),
  (
    'Little Einsteins Neknampur, An International Primary school',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'little_einsteins_neknampur_an_international_primary_school|neknampur|hyderabad',
    true,
    '{}'::text[],
    'Preschool & Primary'
  ),
  (
    'M P P S Building',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'm_p_p_s_building|neknampur|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary Level'
  ),
  (
    'Government High school',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'government_high_school|neknampur|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary to High School'
  ),
  (
    'Wings of Wonder',
    'Neknampur',
    'Hyderabad',
    'Telangana',
    NULL,
    'wings_of_wonder|neknampur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Phoenix Greens School of Learning',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'phoenix_greens_school_of_learning|kokapet|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'The Global Edge School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_global_edge_school|kokapet|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 10/12*'
  ),
  (
    'Johnson Grammar School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'johnson_grammar_school|kokapet|hyderabad',
    true,
    '{IB_PYP}'::text[],
    'Nursery - Grade 6'
  ),
  (
    'Sanctus World School - Best Pre School in',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'sanctus_world_school_best_pre_school_in|kokapet|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Nursery - Grade 12*'
  ),
  (
    'Ingenium World School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'ingenium_world_school|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Little Angel''s High School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'little_angel_s_high_school|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Primary - High School'
  ),
  (
    'Kiddie Den Playschool',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'kiddie_den_playschool|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Playgroup / Preschool'
  ),
  (
    'Kido International Preschool and Daycare',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'kido_international_preschool_and_daycare|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'IKidz Preschool',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'ikidz_preschool|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'BIRLA OPENMINDS PRESCHOOL',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'birla_openminds_preschool|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Kangaroo Kids International Preschool in Kokapet, Hyderabad',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool_in_kokapet_hyderabad|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Matchless Star School',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'matchless_star_school|kokapet|hyderabad',
    true,
    '{}'::text[],
    'Primary - Upper Primary'
  ),
  (
    'MPPS',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'mpps|kokapet|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary'
  ),
  (
    'MPHS',
    'Kokapet',
    'Hyderabad',
    'Telangana',
    NULL,
    'mphs|kokapet|hyderabad',
    true,
    '{SSC}'::text[],
    'Upper Primary - Secondary'
  ),
  (
    'Oakridge International School, Gachibowli',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'oakridge_international_school_gachibowli|khajaguda|hyderabad',
    true,
    '{CBSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'Kairos Global School',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'kairos_global_school|khajaguda|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 10*'
  ),
  (
    'The Indian Public School (TIPS)',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_indian_public_school_tips|khajaguda|hyderabad',
    true,
    '{IGCSE}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'EuroKids Preschool in Khajaguda, Hyderabad',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool_in_khajaguda_hyderabad|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Kidzee Pre School, Chitrapuri hills',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'kidzee_pre_school_chitrapuri_hills|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Ananta Montessori Preschool Khajaguda Hyderabad',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'ananta_montessori_preschool_khajaguda_hyderabad|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Footprints: Play School & Day Care Creche in Khajaguda, Hyderabad',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'footprints_play_school_day_care_creche_in_khajaguda_hyderabad|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Daycare'
  ),
  (
    'Lil Amigos Early Learning Center',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'lil_amigos_early_learning_center|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Beginners World Preschool & Daycare',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'beginners_world_preschool_daycare|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Age 1.5-6; Playgroup - Senior KG'
  ),
  (
    'Aspen Montessori House',
    'Khajaguda',
    'Hyderabad',
    'Telangana',
    NULL,
    'aspen_montessori_house|khajaguda|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Insight International School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'insight_international_school|shaikpet|hyderabad',
    true,
    '{IGCSE}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'Oasis School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'oasis_school|shaikpet|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'International School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'international_school|shaikpet|hyderabad',
    true,
    '{ICSE}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'Sakkubai Memorial High School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'sakkubai_memorial_high_school|shaikpet|hyderabad',
    true,
    '{SSC}'::text[],
    'Grade 1 - Grade 10'
  ),
  (
    'AKSHARA ABHYASA SCHOOL BLOCK 1 (Primary)',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'akshara_abhyasa_school_block_1_primary|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Grade 1 - Grade 8*'
  ),
  (
    'Valli High School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'valli_high_school|shaikpet|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'Stamford Grammar High School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'stamford_grammar_high_school|shaikpet|hyderabad',
    true,
    '{SSC}'::text[],
    'Grade 1 - Grade 10'
  ),
  (
    'Ushodaya High School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'ushodaya_high_school|shaikpet|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'Chanakya Olympiad School',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'chanakya_olympiad_school|shaikpet|hyderabad',
    true,
    '{SSC}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'Oak Brook Academy',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'oak_brook_academy|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Primary Level'
  ),
  (
    'Smartkidz Preschool - Play School in Ou Colony/Manikonda/Shaikpet',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'smartkidz_preschool_play_school_in_ou_colony_manikonda_shaikpet|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'KIDZEE PRESCHOOL',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'kidzee_preschool|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Eurokids preschool',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Footprints Pre-School & Day Care',
    'Shaikpet',
    'Hyderabad',
    'Telangana',
    NULL,
    'footprints_pre_school_day_care|shaikpet|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Bharatiya Vidya Bhavan''s Public School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'bharatiya_vidya_bhavan_s_public_school|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'LKG - Grade 12'
  ),
  (
    'Jubilee Hills Public School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'jubilee_hills_public_school|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - Grade 12'
  ),
  (
    'P. Obul Reddy Public School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'p_obul_reddy_public_school|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - Grade 12'
  ),
  (
    'Bhavan''s Atmakuri Rama Rao School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'bhavan_s_atmakuri_rama_rao_school|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Primary - Secondary / Senior School'
  ),
  (
    'ORCHIDS The International School - CBSE School in',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'orchids_the_international_school_cbse_school_in|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - Secondary Level'
  ),
  (
    'Mosaica International School Of Hyderabad',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'mosaica_international_school_of_hyderabad|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Siddhartha School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'siddhartha_school|jubilee_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Roots School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'roots_school|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'CHIREC International School Jubilee Hills (Preschool) Campus',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'chirec_international_school_jubilee_hills_preschool_campus|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Kangaroo Kids International Preschool in Jubilee Hills, Hyderabad',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool_in_jubilee_hills_hyderabad|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Kangaroo Kids International Preschool in Kavuri Hills, Hyderabad',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool_in_kavuri_hills_hyderabad|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Dibber International Preschools',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'dibber_international_preschools|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Birla Open Minds Pre School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'birla_open_minds_pre_school|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Glenbard International School',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'glenbard_international_school|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Dreamtime Learning Hub Hyderabad',
    'Jubilee Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'dreamtime_learning_hub_hyderabad|jubilee_hills|hyderabad',
    true,
    '{}'::text[],
    'School-age Learning Programs'
  ),
  (
    'Meridian School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'meridian_school|banjara_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 12'
  ),
  (
    'Sultan-ul-Uloom Public School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'sultan_ul_uloom_public_school|banjara_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'St. Alphonsus High School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'st_alphonsus_high_school|banjara_hills|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary - Grade 10'
  ),
  (
    'Lovedale International School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'lovedale_international_school|banjara_hills|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - School Level'
  ),
  (
    'Kalpa School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'kalpa_school|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Primary - Secondary'
  ),
  (
    'Kaushalya Global The Complete School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'kaushalya_global_the_complete_school|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Pre-Primary - School Level'
  ),
  (
    'Serac Ray International School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'serac_ray_international_school|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool - Primary'
  ),
  (
    'Kangaroo Kids International Preschool in Banjara Hills, Hyderabad',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool_in_banjara_hills_hyderabad|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'EuroKids Preschool in Banjara Hills, Hyderabad',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool_in_banjara_hills_hyderabad|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'KLAY Banjara Hills Preschools and Daycare',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'klay_banjara_hills_preschools_and_daycare|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Safari Kid - Banjara Hills, Global Preschool & Daycare',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'safari_kid_banjara_hills_global_preschool_daycare|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Koala Preschool',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'koala_preschool|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Bachpan Play School',
    'Banjara Hills',
    'Hyderabad',
    'Telangana',
    NULL,
    'bachpan_play_school|banjara_hills|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Manthan School',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'manthan_school|tellapur|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Pre-Primary - Grade 12'
  ),
  (
    'Meru International School',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'meru_international_school|tellapur|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Early Years - Grade 12'
  ),
  (
    'Glendale International School IB-PYP',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'glendale_international_school_ib_pyp|tellapur|hyderabad',
    true,
    '{IB_PYP}'::text[],
    'Primary Years / School Level'
  ),
  (
    'Abode School / Abode International School',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'abode_school_abode_international_school|tellapur|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Early Years - Secondary / Senior Grades'
  ),
  (
    'Mondo Skolaris International School, Osman Nagar',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'mondo_skolaris_international_school_osman_nagar|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Early Years - School Level'
  ),
  (
    'JOE International School',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'joe_international_school|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Early Years'
  ),
  (
    'Aspire Preschool & Daycare',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'aspire_preschool_daycare|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Aspire Preschool & Daycare in Tellapur Sayuk - Best Preschool & Daycare My Home Sayuk',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'aspire_preschool_daycare_in_tellapur_sayuk_best_preschool_daycare_my_home_sayuk|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Kidzee',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'kidzee|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Kangaroo Kids International Preschool in Tellapur, Hyderabad',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'kangaroo_kids_international_preschool_in_tellapur_hyderabad|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'EuroKids Preschool in Tellapur, Hyderabad',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool_in_tellapur_hyderabad|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'T.I.M.E KIDS',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    't_i_m_e_kids|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Iris Florets Play School & Daycare',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'iris_florets_play_school_daycare|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Kinderkare Preschool & Daycare',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'kinderkare_preschool_daycare|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Daycare'
  ),
  (
    'Hazelwood International Preschool',
    'Tellapur',
    'Hyderabad',
    'Telangana',
    NULL,
    'hazelwood_international_preschool|tellapur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Mondo Skolaris International School',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'mondo_skolaris_international_school|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Early Years - School Level'
  ),
  (
    'Blue Blocks Complete School',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'blue_blocks_complete_school|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Early Years - School Level'
  ),
  (
    'Little Bridge School',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'little_bridge_school|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Primary Level'
  ),
  (
    'EuroKids Preschool in Osman Nagar, Hyderabad',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool_in_osman_nagar_hyderabad|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'Enriching Minds Preschool',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'enriching_minds_preschool|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Saivika Child Development Centre',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'saivika_child_development_centre|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Early Years / Child Development'
  ),
  (
    'ABODE School Tellapur*',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'abode_school_tellapur|osman_nagar|hyderabad',
    true,
    '{}'::text[],
    'Early Years - School Level'
  ),
  (
    'Meru International School Tellapur*',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'meru_international_school_tellapur|osman_nagar|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Early Years - Senior School'
  ),
  (
    'Manthan School*',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'manthan_school|osman_nagar|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Pre-Primary - Grade 12'
  ),
  (
    'Glendale International School IB-PYP*',
    'Osman Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'glendale_international_school_ib_pyp|osman_nagar|hyderabad',
    true,
    '{IB_PYP}'::text[],
    'Early Years - Primary'
  ),
  (
    'Birla Open Minds International School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'birla_open_minds_international_school|kollur|hyderabad',
    true,
    '{CBSE,IGCSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'Preschool - Grade 12'
  ),
  (
    'Samashti International School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'samashti_international_school|kollur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Early Years - Senior School'
  ),
  (
    'CGR Academy',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'cgr_academy|kollur|hyderabad',
    true,
    '{CBSE,IGCSE}'::text[],
    'Nursery - Grade 8 currently; secondary expansion planned'
  ),
  (
    'The Suraka School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_suraka_school|kollur|hyderabad',
    true,
    '{CBSE,IGCSE,IB_PYP,IB_MYP,IBDP}'::text[],
    'Early Years - School Level'
  ),
  (
    'The Arthah School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_arthah_school|kollur|hyderabad',
    true,
    '{CBSE}'::text[],
    'Primary - School Level'
  ),
  (
    'Vashistha The School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'vashistha_the_school|kollur|hyderabad',
    true,
    '{}'::text[],
    'Primary Level'
  ),
  (
    'Sri Gayatri School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'sri_gayatri_school|kollur|hyderabad',
    true,
    '{}'::text[],
    NULL
  ),
  (
    'Zilla Parishad High School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'zilla_parishad_high_school|kollur|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary - High School'
  ),
  (
    'Government School',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'government_school|kollur|hyderabad',
    true,
    '{SSC}'::text[],
    NULL
  ),
  (
    'EuroKids Preschool in Pati',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'eurokids_preschool_in_pati|kollur|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'CHIRAY Nature Preschool & Daycare',
    'Kollur',
    'Hyderabad',
    'Telangana',
    NULL,
    'chiray_nature_preschool_daycare|kollur|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Daycare'
  ),
  (
    'CornerStone',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'cornerstone|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'UKG - Grade 12'
  ),
  (
    'Infinity World School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'infinity_world_school|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - School Level'
  ),
  (
    'The Creek Planet School - Senior Seeds Campus',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'the_creek_planet_school_senior_seeds_campus|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'LKG - Grade 10'
  ),
  (
    'Academic Heights Public School (AHPS) - Best School in Chanda Nagar I Best CBSE School in',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'academic_heights_public_school_ahps_best_school_in_chanda_nagar_i_best_cbse_school_in|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 10'
  ),
  (
    'Fusion International CBSE School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'fusion_international_cbse_school|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'Pre-Primary - School Level'
  ),
  (
    'BLOSSOMS INTERNATIONAL School Of Excellence',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'blossoms_international_school_of_excellence|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    'Nursery - Grade 7'
  ),
  (
    'Resonance School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'resonance_school|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'Insignis Transnational School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'insignis_transnational_school|chanda_nagar|hyderabad',
    true,
    '{}'::text[],
    'Primary - Secondary Level'
  ),
  (
    'rainbow School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'rainbow_school|chanda_nagar|hyderabad',
    true,
    '{CBSE}'::text[],
    NULL
  ),
  (
    'New National High School',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'new_national_high_school|chanda_nagar|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary - High School'
  ),
  (
    'Viswa vidyalaya high school',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'viswa_vidyalaya_high_school|chanda_nagar|hyderabad',
    true,
    '{SSC}'::text[],
    'Primary - High School'
  ),
  (
    'Ankur''s tree house school',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'ankur_s_tree_house_school|chanda_nagar|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'Little Buddy International Preschool Chandanagar',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'little_buddy_international_preschool_chandanagar|chanda_nagar|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  ),
  (
    'FirstCry Intellitots Preschool & Daycare - Chandanagar, Hyderabad',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'firstcry_intellitots_preschool_daycare_chandanagar_hyderabad|chanda_nagar|hyderabad',
    true,
    '{}'::text[],
    'Preschool / Kindergarten'
  ),
  (
    'KIDZEE PJR Layout Chandanagar',
    'Chanda Nagar',
    'Hyderabad',
    'Telangana',
    NULL,
    'kidzee_pjr_layout_chandanagar|chanda_nagar|hyderabad',
    true,
    '{}'::text[],
    'Playgroup - Kindergarten'
  )
ON CONFLICT (normalized_key) DO UPDATE SET
  name = EXCLUDED.name,
  branch = EXCLUDED.branch,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  pin_code = COALESCE(EXCLUDED.pin_code, schools.pin_code),
  verified = true,
  board_codes = EXCLUDED.board_codes,
  grades_offered = COALESCE(EXCLUDED.grades_offered, schools.grades_offered),
  updated_at = now();
